const $=s=>document.querySelector(s);let accounts=[];
async function request(url,options={}){const response=await fetch(url,options);const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||'Request failed');return data}
function showDashboard(){$('#login').hidden=true;$('#dashboard').hidden=false;loadAll()}
function accountOptions(){return '<option value="">Choose account</option>'+accounts.map(a=>`<option value="${a.id}">${a.name}</option>`).join('')}
async function loadAll(){try{accounts=await request('/api/admin/accounts');$('#accounts').innerHTML=accounts.map(a=>`<div class="account"><span><strong>${a.name}</strong><br><small>${a.cloudName}</small></span><button data-id="${a.id}">Remove</button></div>`).join('')||'<p class="hint">No accounts saved.</p>';document.querySelectorAll('.account-select').forEach(select=>select.innerHTML=accountOptions());document.querySelectorAll('#accounts button').forEach(b=>b.onclick=async()=>{await request(`/api/admin/accounts/${b.dataset.id}`,{method:'DELETE'});loadAll()});const videos=await request('/api/videos');$('#videos').innerHTML=videos.map(v=>`<div class="video">${v.poster?`<img src="${v.poster}" alt="">`:''}<strong>${v.title}</strong><small>${v.category}</small><br><button class="delete" data-id="${v.id}">Delete</button></div>`).join('')||'<p class="hint">No videos published.</p>';document.querySelectorAll('#videos .delete').forEach(b=>b.onclick=async()=>{await request(`/api/admin/videos/${encodeURIComponent(b.dataset.id)}`,{method:'DELETE'});loadAll()});const images=await request('/api/images');$('#images').innerHTML=images.map(image=>`<div class="video"><img src="${image.imageUrl}" alt=""><strong>${image.title}</strong><small>${image.category}</small><br><button class="delete" data-id="${image.id}">Delete</button></div>`).join('')||'<p class="hint">No images published.</p>';document.querySelectorAll('#images .delete').forEach(b=>b.onclick=async()=>{await request(`/api/admin/images/${encodeURIComponent(b.dataset.id)}`,{method:'DELETE'});loadAll()})}catch(e){$('#login').hidden=false;$('#dashboard').hidden=true}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await request('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('#password').value})});showDashboard()}catch(err){$('#loginMessage').textContent=err.message}};
$('#accountForm').onsubmit=async e=>{e.preventDefault();try{await request('/api/admin/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});e.target.reset();loadAll()}catch(err){alert(err.message)}};
$('#uploadForm').onsubmit=async e=>{e.preventDefault();$('#uploadMessage').textContent='Uploading…';try{await request('/api/admin/upload',{method:'POST',body:new FormData(e.target)});e.target.reset();$('#uploadMessage').textContent='Video published.';loadAll()}catch(err){$('#uploadMessage').textContent=err.message}};
$('#imageForm').onsubmit=async e=>{e.preventDefault();$('#imageMessage').textContent='Uploading…';try{await request('/api/admin/images',{method:'POST',body:new FormData(e.target)});e.target.reset();$('#imageMessage').textContent='Image published.';loadAll()}catch(err){$('#imageMessage').textContent=err.message}};
$('#logout').onclick=async()=>{await request('/api/admin/logout',{method:'POST'});location.reload()};loadAll();
