/* Replace this with the /exec URL from your deployed Google Apps Script web app. */
const GOOGLE_DRIVE_VIDEO_API = 'https://script.google.com/macros/s/AKfycbzrIpwQ1VxGYwy7Qput3GjXgfEHqe0Jg4DCdekqfouy6B3ZN2adBrxFL1QFPuNar09J/exec';

(() => {
  const grid = document.getElementById('videoGrid');
  const status = document.getElementById('videoStatus');
  const filters = document.getElementById('videoFilters');
  const search = document.getElementById('videoSearch');
  const modal = document.getElementById('videoModal');
  const gallery = document.querySelector('.gallery-container');
  let videos = [], salonImages = [], activeCategory = 'All';
  const escape = text => { const el = document.createElement('span'); el.textContent = text || ''; return el.innerHTML; };
  const fileId = value => { const match = String(value || '').match(/(?:\/d\/|[?&]id=)([-\w]{10,})/); return match ? match[1] : value; };
  function drawFilters() { const categories = ['All', ...new Set(videos.map(v => v.category).filter(Boolean))]; filters.innerHTML = categories.map(category => `<button class="video-filter ${category === activeCategory ? 'active' : ''}" data-category="${escape(category)}">${escape(category)}</button>`).join(''); filters.querySelectorAll('button').forEach(button => button.onclick = () => { activeCategory = button.dataset.category; drawFilters(); draw(); }); }
  function draw() { const query = search.value.toLowerCase().trim(); const shown = videos.filter(video => (activeCategory === 'All' || video.category === activeCategory) && [video.title, video.category, video.artist, video.description].join(' ').toLowerCase().includes(query)); status.textContent = shown.length ? `${shown.length} salon video${shown.length === 1 ? '' : 's'} to explore.` : 'No salon videos found.'; grid.innerHTML = shown.map(video => `<article class="video-card" data-id="${escape(video.id)}"><div class="video-thumb"><img src="https://drive.google.com/thumbnail?id=${encodeURIComponent(video.fileId)}&sz=w1000" alt="${escape(video.title)}" loading="lazy"><span class="video-play">▶</span></div><div class="video-card-body"><p class="video-category">${escape(video.category || 'SALON VIDEO')}</p><h4>${escape(video.title || 'Salon video')}</h4><p>${escape(video.artist || 'Mallesha Hair Studio')}</p></div></article>`).join('') || '<p class="video-empty">No videos match your search.</p>'; grid.querySelectorAll('.video-card').forEach(card => card.onclick = () => openVideo(videos.find(video => String(video.id) === card.dataset.id))); }
  const player = document.getElementById('videoPlayer');
  function closeVideo() { modal.classList.remove('active'); modal.setAttribute('aria-hidden', 'true'); player.src = ''; }
  function openVideo(video) { player.src = `https://drive.google.com/file/d/${encodeURIComponent(video.fileId)}/preview`; document.getElementById('modalVideoCategory').textContent = video.category || 'SALON VIDEO'; document.getElementById('modalVideoTitle').textContent = video.title || 'Salon video'; document.getElementById('modalVideoDescription').textContent = video.description || ''; document.getElementById('openDriveVideo').href = `https://drive.google.com/file/d/${encodeURIComponent(video.fileId)}/view`; modal.classList.add('active'); modal.setAttribute('aria-hidden', 'false'); }
  document.getElementById('closeVideoModal').onclick = closeVideo; search.oninput = draw;
  const categoryKey = value => String(value || '').toLowerCase().replace(/colour/g, 'color').replace(/[^a-z]/g, '');
  function setupImageGallery(images) { if (!gallery) return; salonImages = images.map(image => ({ ...image, fileId:fileId(image.fileId || image.driveUrl || image.viewUrl) })).filter(image => image.fileId); gallery.querySelectorAll('.gallery-item').forEach(item => { item.tabIndex = 0; item.setAttribute('role', 'button'); item.onclick = () => openImageCategory(item.textContent); item.onkeydown = event => { if (event.key === 'Enter' || event.key === ' ') openImageCategory(item.textContent); }; }); }
  function openFullImage(image) { const popup = document.createElement('dialog'); popup.className = 'full-image-modal'; popup.innerHTML = `<button class="full-image-close" aria-label="Close image">&times;</button><img src="https://drive.google.com/thumbnail?id=${encodeURIComponent(image.fileId)}&sz=w2000" alt="${escape(image.title)}"><div><strong>${escape(image.title)}</strong><a href="https://drive.google.com/file/d/${encodeURIComponent(image.fileId)}/view" target="_blank" rel="noopener">Open in Google Drive &rarr;</a></div>`; document.body.appendChild(popup); const close = () => popup.remove(); popup.querySelector('.full-image-close').onclick = () => { popup.close(); close(); }; popup.onclose = close; popup.onclick = event => { if (event.target === popup) popup.close(); }; popup.showModal(); }
  function openImageCategory(category) { const selected = salonImages.filter(image => categoryKey(image.category) === categoryKey(category)); const popup = document.createElement('dialog'); popup.className = 'image-modal'; popup.innerHTML = `<button class="image-close" aria-label="Close images">&times;</button><div class="image-modal-content"><p>${escape(category)}</p><h3>${escape(category)} Gallery</h3><div class="image-grid">${selected.map((image, index) => `<button class="image-view" data-index="${index}"><img src="https://drive.google.com/thumbnail?id=${encodeURIComponent(image.fileId)}&sz=w1000" alt="${escape(image.title)}" loading="lazy"><span>${escape(image.title)}</span></button>`).join('') || '<p class="image-empty">No images have been added to this category yet.</p>'}</div></div>`; document.body.appendChild(popup); popup.querySelectorAll('.image-view').forEach(button => button.onclick = () => openFullImage(selected[Number(button.dataset.index)])); const close = () => popup.remove(); popup.querySelector('.image-close').onclick = () => { popup.close(); close(); }; popup.onclose = close; popup.onclick = event => { if (event.target === popup) popup.close(); }; popup.showModal(); }
  function showVideos(data) { if (data && data.success === false) throw Error(data.message || 'The Apps Script returned an error.'); const items = Array.isArray(data) ? data : (data.videos || []); videos = items.map(video => ({ ...video, id: video.id || video.fileId, fileId: fileId(video.fileId || video.driveUrl || video.viewUrl) })).filter(video => video.fileId); setupImageGallery(Array.isArray(data) ? [] : (data.images || [])); drawFilters(); draw(); }
  function loadJsonp() { const callback = `salonVideos_${Date.now()}`; const script = document.createElement('script'); window[callback] = data => { try { showVideos(data); } catch (error) { status.textContent = `Unable to load videos: ${error.message}`; } finally { delete window[callback]; script.remove(); } }; script.onerror = () => { status.textContent = 'Unable to load videos. Redeploy Apps Script with the updated Code.gs and set access to Anyone.'; delete window[callback]; script.remove(); }; script.src = `${GOOGLE_DRIVE_VIDEO_API}${GOOGLE_DRIVE_VIDEO_API.includes('?') ? '&' : '?'}callback=${callback}`; document.head.appendChild(script); }
  async function load() { if (GOOGLE_DRIVE_VIDEO_API.startsWith('PASTE_')) { status.textContent = 'Connect your Google Apps Script URL in script.js to show salon videos.'; return; } try { const data = await fetch(GOOGLE_DRIVE_VIDEO_API).then(response => response.json()); showVideos(data); } catch (error) { loadJsonp(); } }
  load();
})();
