/* Add your MP4 files to the videos folder and list them in videos.json. */
const LOCAL_VIDEOS_URL = '/api/videos';

(() => {
  const grid = document.getElementById('videoGrid');
  const status = document.getElementById('videoStatus');
  const filters = document.getElementById('videoFilters');
  const search = document.getElementById('videoSearch');
  const modal = document.getElementById('videoModal');
  const gallery = document.querySelector('.gallery-container');
  let videos = [], salonImages = [], activeCategory = 'All';
  const escape = text => { const el = document.createElement('span'); el.textContent = text || ''; return el.innerHTML; };
  const fileId = value => { const match = String(value || '').match(/(?:\/d\/|[?&]id=)([-\w]{10,})/); return match ? match[1] : value; };
  function drawFilters() { const categories = ['All', ...new Set(videos.map(v => v.category).filter(Boolean))]; filters.innerHTML = categories.map(category => `<button class="video-filter ${category === activeCategory ? 'active' : ''}" data-category="${escape(category)}">${escape(category)}</button>`).join(''); filters.querySelectorAll('button').forEach(button => button.onclick = () => { activeCategory = button.dataset.category; drawFilters(); draw(); }); }
  function draw() { const query = search.value.toLowerCase().trim(); const shown = videos.filter(video => (activeCategory === 'All' || video.category === activeCategory) && [video.title, video.category, video.artist, video.description].join(' ').toLowerCase().includes(query)); status.textContent = shown.length ? `${shown.length} salon video${shown.length === 1 ? '' : 's'} to explore.` : 'No salon videos found.'; grid.innerHTML = shown.map(video => `<article class="video-card" data-id="${escape(video.id)}"><div class="video-thumb">${video.poster ? `<img src="${escape(video.poster)}" alt="${escape(video.title)}" loading="lazy">` : '<span class="video-no-poster">SALON VIDEO</span>'}<span class="video-play">▶</span></div><div class="video-card-body"><p class="video-category">${escape(video.category || 'SALON VIDEO')}</p><h4>${escape(video.title || 'Salon video')}</h4><p>${escape(video.artist || 'Mallesha Hair Studio')}</p></div></article>`).join('') || '<p class="video-empty">No videos match your search.</p>'; grid.querySelectorAll('.video-card').forEach(card => card.onclick = () => openVideo(videos.find(video => String(video.id) === card.dataset.id))); }
  const player = document.getElementById('videoPlayer'), videoBackdrop = document.getElementById('videoBackdrop'), playPause = document.getElementById('videoPlayPause'), time = document.getElementById('videoTime'), mute = document.getElementById('videoMute');
  const formatTime = seconds => !Number.isFinite(seconds) ? '0:00' : `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, '0')}`;
  function syncPlayer() { playPause.textContent = player.paused ? '▶' : '❚❚'; time.textContent = `${formatTime(player.currentTime)} / ${formatTime(player.duration)}`; mute.textContent = player.muted || !player.volume ? '🔇' : '🔊'; }
  function togglePlay() { if (player.paused) player.play().catch(() => {}); else player.pause(); }
  playPause.onclick = togglePlay; player.onclick = togglePlay; player.onplay = () => { videoBackdrop.play().catch(() => {}); syncPlayer(); }; player.onpause = () => { videoBackdrop.pause(); syncPlayer(); }; player.ontimeupdate = () => { if (Math.abs(videoBackdrop.currentTime - player.currentTime) > .4) videoBackdrop.currentTime = player.currentTime; syncPlayer(); }; player.onloadedmetadata = syncPlayer; player.onvolumechange = syncPlayer;
  document.getElementById('videoBack10').onclick = () => { player.currentTime = Math.max(0, player.currentTime - 10); }; document.getElementById('videoForward10').onclick = () => { player.currentTime = Math.min(player.duration || Infinity, player.currentTime + 10); }; mute.onclick = () => { player.muted = !player.muted; }; document.getElementById('videoFullscreen').onclick = () => document.querySelector('.custom-video-player').requestFullscreen?.();
  function closeVideo() { player.pause(); videoBackdrop.pause(); player.removeAttribute('src'); videoBackdrop.removeAttribute('src'); player.load(); videoBackdrop.load(); modal.classList.remove('active'); modal.setAttribute('aria-hidden', 'true'); document.body.classList.remove('video-open'); }
  function openVideo(video) { player.src = video.videoUrl; videoBackdrop.src = video.videoUrl; player.load(); videoBackdrop.load(); document.getElementById('modalVideoCategory').textContent = video.category || 'SALON VIDEO'; document.getElementById('modalVideoTitle').textContent = video.title || 'Salon video'; document.getElementById('modalVideoDescription').textContent = video.description || ''; document.getElementById('openDriveVideo').href = video.videoUrl; document.getElementById('openDriveVideo').textContent = 'Open video file ↗'; modal.classList.add('active'); modal.setAttribute('aria-hidden', 'false'); document.body.classList.add('video-open'); }
  player.onerror = () => { document.getElementById('modalVideoDescription').textContent = 'This MP4 file could not be loaded. Check its path in videos.json.'; };
  document.getElementById('closeVideoModal').onclick = closeVideo; search.oninput = draw;
  const categoryKey = value => String(value || '').toLowerCase().replace(/colour/g, 'color').replace(/[^a-z]/g, '');
  function setupImageGallery(images) { if (!gallery) return; salonImages = images.map(image => ({ ...image, fileId:fileId(image.fileId || image.driveUrl || image.viewUrl) })).filter(image => image.fileId); gallery.querySelectorAll('.gallery-item').forEach(item => { item.tabIndex = 0; item.setAttribute('role', 'button'); item.onclick = () => openImageCategory(item.textContent); item.onkeydown = event => { if (event.key === 'Enter' || event.key === ' ') openImageCategory(item.textContent); }; }); }
  function openFullImage(image) { const popup = document.createElement('dialog'); popup.className = 'full-image-modal'; popup.innerHTML = `<button class="full-image-close" aria-label="Close image">&times;</button><img src="https://drive.google.com/thumbnail?id=${encodeURIComponent(image.fileId)}&sz=w2000" alt="${escape(image.title)}"><div><strong>${escape(image.title)}</strong><a href="https://drive.google.com/file/d/${encodeURIComponent(image.fileId)}/view" target="_blank" rel="noopener">Open in Google Drive &rarr;</a></div>`; document.body.appendChild(popup); const close = () => popup.remove(); popup.querySelector('.full-image-close').onclick = () => { popup.close(); close(); }; popup.onclose = close; popup.onclick = event => { if (event.target === popup) popup.close(); }; popup.showModal(); }
  function openImageCategory(category) { const selected = salonImages.filter(image => categoryKey(image.category) === categoryKey(category)); const popup = document.createElement('dialog'); popup.className = 'image-modal'; popup.innerHTML = `<button class="image-close" aria-label="Close images">&times;</button><div class="image-modal-content"><p>${escape(category)}</p><h3>${escape(category)} Gallery</h3><div class="image-grid">${selected.map((image, index) => `<button class="image-view" data-index="${index}"><img src="https://drive.google.com/thumbnail?id=${encodeURIComponent(image.fileId)}&sz=w1000" alt="${escape(image.title)}" loading="lazy"><span>${escape(image.title)}</span></button>`).join('') || '<p class="image-empty">No images have been added to this category yet.</p>'}</div></div>`; document.body.appendChild(popup); popup.querySelectorAll('.image-view').forEach(button => button.onclick = () => openFullImage(selected[Number(button.dataset.index)])); const close = () => popup.remove(); popup.querySelector('.image-close').onclick = () => { popup.close(); close(); }; popup.onclose = close; popup.onclick = event => { if (event.target === popup) popup.close(); }; popup.showModal(); }
  function showVideos(data) { const items = Array.isArray(data) ? data : (data.videos || []); videos = items.map(video => ({ ...video, id: video.id || video.videoUrl })).filter(video => video.videoUrl); drawFilters(); draw(); }
  async function load() { try { const data = await fetch(LOCAL_VIDEOS_URL).then(response => { if (!response.ok) throw Error('Admin server is not running. Deploy this project as a Render Web Service.'); return response.json(); }); showVideos(data); } catch (error) { status.textContent = `Unable to load videos: ${error.message}`; } }
  load();
})();
