const express=require('express'), multer=require('multer'), cloudinary=require('cloudinary').v2, mysql=require('mysql2/promise'), crypto=require('node:crypto'), fs=require('node:fs'), path=require('node:path');
const app=express(), PORT=process.env.PORT||3000, ADMIN_PASSWORD=process.env.ADMIN_PASSWORD, DB_NAME=process.env.TIDB_DATABASE||'salon_admin';
const MASTER_KEY=crypto.createHash('sha256').update(process.env.MASTER_KEY||'').digest(), sessions=new Set(); let pool;
const upload=multer({dest:path.join('/tmp','salon-uploads'),limits:{fileSize:100*1024*1024}});
const dbConfig={host:process.env.TIDB_HOST,port:Number(process.env.TIDB_PORT||4000),user:process.env.TIDB_USER,password:process.env.TIDB_PASSWORD,ssl:process.env.TIDB_SSL==='true'?{minVersion:'TLSv1.2',rejectUnauthorized:true}:undefined};
function encrypt(value){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',MASTER_KEY,iv),text=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return `${iv.toString('base64')}.${cipher.getAuthTag().toString('base64')}.${text.toString('base64')}`}
function decrypt(value){const [iv,tag,text]=value.split('.').map(x=>Buffer.from(x,'base64')),decipher=crypto.createDecipheriv('aes-256-gcm',MASTER_KEY,iv);decipher.setAuthTag(tag);return Buffer.concat([decipher.update(text),decipher.final()]).toString('utf8')}
function token(req){return(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('salon_admin='))?.slice(12)}
function admin(req,res,next){return sessions.has(token(req))?next():res.status(401).json({error:'Please sign in.'})}
async function initDb(){if(!/^[A-Za-z0-9_]+$/.test(DB_NAME))throw Error('TIDB_DATABASE must contain only letters, numbers, and underscores.');const root=await mysql.createConnection(dbConfig);await root.query(`CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\``);await root.end();pool=mysql.createPool({...dbConfig,database:DB_NAME,waitForConnections:true,connectionLimit:5});await pool.query(`CREATE TABLE IF NOT EXISTS cloudinary_accounts (id VARCHAR(36) PRIMARY KEY,name VARCHAR(120) NOT NULL,cloud_name VARCHAR(120) NOT NULL,encrypted LONGTEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);await pool.query(`CREATE TABLE IF NOT EXISTS videos (id VARCHAR(255) PRIMARY KEY,title VARCHAR(255) NOT NULL,category VARCHAR(120),artist VARCHAR(120),description TEXT,video_url TEXT NOT NULL,poster TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);await pool.query(`CREATE TABLE IF NOT EXISTS images (id VARCHAR(255) PRIMARY KEY,title VARCHAR(255) NOT NULL,category VARCHAR(120) NOT NULL,description TEXT,image_url TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);try{await pool.query('ALTER TABLE images ADD COLUMN description TEXT')}catch(error){if(error.code!=='ER_DUP_FIELDNAME')throw error}}
app.use(express.json());app.use(express.static(__dirname));
app.get('/api/videos',async(req,res)=>{const[rows]=await pool.query('SELECT id,title,category,artist,description,video_url AS videoUrl,poster FROM videos ORDER BY created_at DESC');res.json(rows)});
app.get('/api/images',async(req,res)=>{const[rows]=await pool.query('SELECT id,title,category,description,image_url AS imageUrl FROM images ORDER BY created_at DESC');res.json(rows)});
app.post('/api/admin/login',(req,res)=>{if(!ADMIN_PASSWORD||!req.body.password||req.body.password!==ADMIN_PASSWORD)return res.status(401).json({error:'Invalid password.'});const id=crypto.randomBytes(32).toString('hex');sessions.add(id);res.setHeader('Set-Cookie',`salon_admin=${id}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800`);res.json({success:true})});
app.post('/api/admin/logout',admin,(req,res)=>{sessions.delete(token(req));res.setHeader('Set-Cookie','salon_admin=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');res.json({success:true})});
app.get('/api/admin/accounts',admin,async(req,res)=>{const[rows]=await pool.query('SELECT id,name,cloud_name AS cloudName FROM cloudinary_accounts ORDER BY created_at DESC');res.json(rows)});
app.post('/api/admin/accounts',admin,async(req,res)=>{const{name,cloudName,apiKey,apiSecret}=req.body;if(![name,cloudName,apiKey,apiSecret].every(Boolean))return res.status(400).json({error:'Complete every account field.'});await pool.execute('INSERT INTO cloudinary_accounts (id,name,cloud_name,encrypted) VALUES (?,?,?,?)',[crypto.randomUUID(),name,cloudName,encrypt(JSON.stringify({apiKey,apiSecret}))]);res.status(201).json({success:true})});
app.delete('/api/admin/accounts/:id',admin,async(req,res)=>{await pool.execute('DELETE FROM cloudinary_accounts WHERE id=?',[req.params.id]);res.json({success:true})});
app.post('/api/admin/upload-signature',admin,async(req,res)=>{const[accounts]=await pool.execute('SELECT * FROM cloudinary_accounts WHERE id=?',[req.body.accountId]);if(!accounts[0])return res.status(400).json({error:'Choose a Cloudinary account.'});const resourceType=req.body.resourceType==='image'?'image':'video',folder=resourceType==='image'?'salon-images':'salon-videos',timestamp=Math.floor(Date.now()/1000),{apiKey,apiSecret}=JSON.parse(decrypt(accounts[0].encrypted));res.json({cloudName:accounts[0].cloud_name,apiKey,timestamp,folder,signature:cloudinary.utils.api_sign_request({timestamp,folder},apiSecret)})});
app.post('/api/admin/videos',admin,async(req,res)=>{const{publicId,title,category,artist,description,videoUrl,poster}=req.body;if(!publicId||!videoUrl)return res.status(400).json({error:'Upload the video first.'});await pool.execute('INSERT INTO videos (id,title,category,artist,description,video_url,poster) VALUES (?,?,?,?,?,?,?)',[publicId,title||'Salon video',category||'Salon video',artist||'Mallesha Hair Studio',description||'',videoUrl,poster||'']);res.status(201).json({success:true})});
app.post('/api/admin/images/record',admin,async(req,res)=>{const{publicId,title,category,description,imageUrl}=req.body;if(!publicId||!imageUrl)return res.status(400).json({error:'Upload the image first.'});await pool.execute('INSERT INTO images (id,title,category,description,image_url) VALUES (?,?,?,?,?)',[publicId,title||'Salon image',category||'Salon',description||'',imageUrl]);res.status(201).json({success:true})});
app.post('/api/admin/upload',admin,upload.single('video'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'Choose an MP4 video.'});const[accounts]=await pool.execute('SELECT * FROM cloudinary_accounts WHERE id=?',[req.body.accountId]);if(!accounts[0])return res.status(400).json({error:'Choose a Cloudinary account.'});const{apiKey,apiSecret}=JSON.parse(decrypt(accounts[0].encrypted));cloudinary.config({cloud_name:accounts[0].cloud_name,api_key:apiKey,api_secret:apiSecret,secure:true});const result=await cloudinary.uploader.upload(req.file.path,{resource_type:'video',folder:'salon-videos'}),poster=result.secure_url.replace('/upload/','/upload/so_0/').replace(/\.[^.]+$/,'.jpg');await pool.execute('INSERT INTO videos (id,title,category,artist,description,video_url,poster) VALUES (?,?,?,?,?,?,?)',[result.public_id,req.body.title||req.file.originalname,req.body.category||'Salon video',req.body.artist||'Mallesha Hair Studio',req.body.description||'',result.secure_url,poster]);fs.unlink(req.file.path,()=>{});res.status(201).json({success:true})}catch(error){if(req.file)fs.unlink(req.file.path,()=>{});console.error(error);res.status(500).json({error:'Upload failed. Check Cloudinary details and TiDB connection.'})}});
app.post('/api/admin/images',admin,upload.single('image'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'Choose an image.'});const[accounts]=await pool.execute('SELECT * FROM cloudinary_accounts WHERE id=?',[req.body.accountId]);if(!accounts[0])return res.status(400).json({error:'Choose a Cloudinary account.'});const{apiKey,apiSecret}=JSON.parse(decrypt(accounts[0].encrypted));cloudinary.config({cloud_name:accounts[0].cloud_name,api_key:apiKey,api_secret:apiSecret,secure:true});const result=await cloudinary.uploader.upload(req.file.path,{resource_type:'image',folder:'salon-images',transformation:[{quality:'auto',fetch_format:'auto'}]});await pool.execute('INSERT INTO images (id,title,category,description,image_url) VALUES (?,?,?,?,?)',[result.public_id,req.body.title||req.file.originalname,req.body.category||'Salon',req.body.description||'',result.secure_url]);fs.unlink(req.file.path,()=>{});res.status(201).json({success:true})}catch(error){if(req.file)fs.unlink(req.file.path,()=>{});console.error(error);res.status(500).json({error:'Image upload failed. Check Cloudinary details and TiDB connection.'})}});
app.delete('/api/admin/videos/:id',admin,async(req,res)=>{await pool.execute('DELETE FROM videos WHERE id=?',[req.params.id]);res.json({success:true})});
app.delete('/api/admin/images/:id',admin,async(req,res)=>{await pool.execute('DELETE FROM images WHERE id=?',[req.params.id]);res.json({success:true})});
initDb().then(()=>app.listen(PORT,()=>console.log(`Salon admin with TiDB running on ${PORT}`))).catch(error=>{console.error('TiDB startup failed:',error);process.exit(1)});
